export interface ModelEntry {
  id: string;
  name: string;
  description: string;
  url: string;
  filename: string;
  sizeBytes: number;
  sizeLabel: string;
  quantization: string;
  parameters: string;
  recommended?: boolean;
}

export const MODEL_CATALOG: ModelEntry[] = [
  // ===== RECOMMENDED (Lightest to Heaviest) =====
  {
    id: 'llama3.2-1b-q4',
    name: 'Llama 3.2 1B Instruct',
    description:
      'Fastest option. Multilingual instruction-following. ~5 tokens/sec on mobile. Perfect for limited devices. RECOMMENDED.',
    url: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf',
    filename: 'Llama-3.2-1B-Instruct-Q4_K_M.gguf',
    sizeBytes: 810_000_000,
    sizeLabel: '~810 MB',
    quantization: 'Q4_K_M',
    parameters: '1B',
    recommended: true,
  },
  {
    id: 'phi3.5-mini-q4',
    name: 'Phi-3.5 Mini',
    description: "Microsoft's powerhouse. Best reasoning per MB. ~12 tokens/sec. HIGHLY RECOMMENDED.",
    url: 'https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf',
    filename: 'Phi-3.5-mini-instruct-Q4_K_M.gguf',
    sizeBytes: 2_420_000_000,
    sizeLabel: '~2.42 GB',
    quantization: 'Q4_K_M',
    parameters: '3.8B',
    recommended: true,
  },

  // ===== LIGHTEST (1B - 1.7B) =====
  {
    id: 'pythia-1.4b-q4',
    name: 'Pythia 1.4B',
    description: 'Research LLM for English text generation. Very fast on mobile. 1.4B params.',
    url: 'https://huggingface.co/tensorblock/pythia-1.4b-GGUF/resolve/main/pythia-1.4b-Q4_K_M.gguf',
    filename: 'pythia-1.4b-Q4_K_M.gguf',
    sizeBytes: 850_000_000,
    sizeLabel: '~850 MB',
    quantization: 'Q4_K_M',
    parameters: '1.4B',
  },
  {
    id: 'qwen2.5-1.5b-q4',
    name: 'Qwen 2.5 1.5B',
    description: 'Multilingual (including Indonesian). Compact and capable. 1.5B params.',
    url: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf',
    filename: 'qwen2.5-1.5b-instruct-q4_k_m.gguf',
    sizeBytes: 1_000_000_000,
    sizeLabel: '~1 GB',
    quantization: 'Q4_K_M',
    parameters: '1.5B',
  },
  {
    id: 'smollm2-1.7b-q4',
    name: 'SmolLM2 1.7B',
    description: 'Tiny and fast. Great for devices with very limited RAM. 1.7B params.',
    url: 'https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF/resolve/main/SmolLM2-1.7B-Instruct-Q4_K_M.gguf',
    filename: 'SmolLM2-1.7B-Instruct-Q4_K_M.gguf',
    sizeBytes: 1_100_000_000,
    sizeLabel: '~1.1 GB',
    quantization: 'Q4_K_M',
    parameters: '1.7B',
  },

  // ===== LIGHT (2B - 2.7B) =====
  {
    id: 'gemma2-2b-it-q4',
    name: 'Gemma 2 2B Italian',
    description: "Google's efficient model fine-tuned for Italian conversations. 2B params.",
    url: 'https://huggingface.co/BafS/gemma-2-2b-it-Q4_K_M-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf',
    filename: 'gemma-2-2b-it-Q4_K_M.gguf',
    sizeBytes: 1_710_000_000,
    sizeLabel: '~1.71 GB',
    quantization: 'Q4_K_M',
    parameters: '2B',
  },
  {
    id: 'phi-2-q4',
    name: 'Phi-2 (Microsoft)',
    description: 'Exceptional quality-to-size ratio. Strong at QA, coding, dialogue. 2.7B params.',
    url: 'https://huggingface.co/TheBloke/phi-2-GGUF/resolve/main/phi-2.Q4_K_M.gguf',
    filename: 'phi-2.Q4_K_M.gguf',
    sizeBytes: 1_790_000_000,
    sizeLabel: '~1.79 GB',
    quantization: 'Q4_K_M',
    parameters: '2.7B',
  },

  // ===== MODERATE (3B) =====
  {
    id: 'rocket-3b-q4',
    name: 'Rocket 3B',
    description: 'Trained on instruction chat data. Strong conversational ability. 3B params.',
    url: 'https://huggingface.co/TheBloke/rocket-3B-GGUF/resolve/main/rocket-3b.Q4_K_M.gguf',
    filename: 'rocket-3b.Q4_K_M.gguf',
    sizeBytes: 1_710_000_000,
    sizeLabel: '~1.71 GB',
    quantization: 'Q4_K_M',
    parameters: '3B',
  },
  {
    id: 'stable-code-3b-q4',
    name: 'Stable Code 3B',
    description: 'Specialized for code generation and analysis. 3B params.',
    url: 'https://huggingface.co/TheBloke/stable-code-3b-GGUF/resolve/main/stable-code-3b.Q4_K_M.gguf',
    filename: 'stable-code-3b.Q4_K_M.gguf',
    sizeBytes: 1_710_000_000,
    sizeLabel: '~1.71 GB',
    quantization: 'Q4_K_M',
    parameters: '3B',
  },
  {
    id: 'dolly-v2-3b-q4',
    name: 'Dolly v2 3B',
    description: 'Instructional chatbot trained on Dolly dataset. 3B params.',
    url: 'https://huggingface.co/mradermacher/dolly-v2-3b-GGUF/resolve/main/dolly-v2-3b-Q4_K_M.gguf',
    filename: 'dolly-v2-3b-Q4_K_M.gguf',
    sizeBytes: 1_790_000_000,
    sizeLabel: '~1.79 GB',
    quantization: 'Q4_K_M',
    parameters: '3B',
  },
  {
    id: 'ministral-3b-q4',
    name: 'Ministral 3B Instruct',
    description: 'Mistral 3B instruct version. Good for chat and QA. 3B params.',
    url: 'https://huggingface.co/matrixportalx/Ministral-3b-instruct-Q4_K_M-GGUF/resolve/main/ministral-3b-instruct-q4_k_m.gguf',
    filename: 'ministral-3b-instruct-q4_k_m.gguf',
    sizeBytes: 2_000_000_000,
    sizeLabel: '~2.00 GB',
    quantization: 'Q4_K_M',
    parameters: '3B',
  },
  {
    id: 'mistral-3b-q4',
    name: 'Mistral 3B',
    description: 'Mistral-based conversational model. Efficient and capable. 3B params.',
    url: 'https://huggingface.co/Tech-Meld/HX-Mistral-3B_v0.1-Q4_K_M-GGUF/resolve/main/HX-Mistral-3B_v0.1-Q4_K_M.gguf',
    filename: 'HX-Mistral-3B_v0.1-Q4_K_M.gguf',
    sizeBytes: 2_280_000_000,
    sizeLabel: '~2.28 GB',
    quantization: 'Q4_K_M',
    parameters: '3B',
  },
  {
    id: 'llama3.2-3b-q4',
    name: 'Llama 3.2 3B Instruct',
    description: 'Better reasoning. Good for retrieval, summarization. ~10 tokens/sec. 3B params.',
    url: 'https://huggingface.co/lmstudio-community/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf',
    filename: 'Llama-3.2-3B-Instruct-Q4_K_M.gguf',
    sizeBytes: 2_020_000_000,
    sizeLabel: '~2.02 GB',
    quantization: 'Q4_K_M',
    parameters: '3B',
  },

  // ===== MEDIUM (4B - 3.8B) =====
  {
    id: 'phi3-mini-q4',
    name: 'Phi-3 mini 4K-8K',
    description: 'Microsoft Phi-3 mini. Strong instruction-following and coding. 3.8B params.',
    url: 'https://huggingface.co/SixOpen/Phi-3-mini-4k-instruct-Q4_K_M-GGUF/resolve/main/Phi-3-mini-4k-instruct-Q4_K_M.gguf',
    filename: 'Phi-3-mini-4k-instruct-Q4_K_M.gguf',
    sizeBytes: 2_390_000_000,
    sizeLabel: '~2.39 GB',
    quantization: 'Q4_K_M',
    parameters: '3.8B',
  },
  {
    id: 'gemma-3-4b-it-q4',
    name: 'Gemma 3 4B Italian',
    description: 'Google Gemma 4B fine-tuned for Italian. Conversational and QA. 4B params.',
    url: 'https://huggingface.co/Aldaris/gemma-3-4b-it-Q4_K_M-GGUF/resolve/main/gemma-3-4b-it-Q4_K_M.gguf',
    filename: 'gemma-3-4b-it-Q4_K_M.gguf',
    sizeBytes: 2_490_000_000,
    sizeLabel: '~2.49 GB',
    quantization: 'Q4_K_M',
    parameters: '4B',
  },
  {
    id: 'qwen3-4b-q4',
    name: 'Qwen-3 4B',
    description: 'Multilingual reasoning. Strong at code, math, logic. Two thinking modes. 4B params.',
    url: 'https://huggingface.co/Qwen/Qwen3-4B-GGUF/resolve/main/qwen3-4b-q4_k_m.gguf',
    filename: 'qwen3-4b-q4_k_m.gguf',
    sizeBytes: 2_500_000_000,
    sizeLabel: '~2.50 GB',
    quantization: 'Q4_K_M',
    parameters: '4B',
  },

  // ===== HIGH (7B) =====
  {
    id: 'llama2-7b-chat-q4',
    name: 'Llama 2 7B Chat',
    description: 'General-purpose chat. Stable and reliable. ~3 tokens/sec on mobile. 7B params.',
    url: 'https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/resolve/main/llama-2-7b-chat.Q4_K_M.gguf',
    filename: 'llama-2-7b-chat.Q4_K_M.gguf',
    sizeBytes: 4_080_000_000,
    sizeLabel: '~4.08 GB',
    quantization: 'Q4_K_M',
    parameters: '7B',
  },
  {
    id: 'mpt-7b-instruct-q4',
    name: 'MPT-7B Instruct',
    description: 'Short-form instruction tuned. Derived from Dolly/RLHF training. 7B params.',
    url: 'https://huggingface.co/maddes8cht/mosaicml-mpt-7b-instruct-gguf/resolve/main/mpt-7b-instruct-Q4_K_M.gguf',
    filename: 'mpt-7b-instruct-Q4_K_M.gguf',
    sizeBytes: 4_330_000_000,
    sizeLabel: '~4.33 GB',
    quantization: 'Q4_K_M',
    parameters: '7B',
  },
  {
    id: 'mistral-7b-instruct-q4',
    name: 'Mistral 7B Instruct',
    description: 'Strong reasoning, mathematics, summarization. ~3 tokens/sec. 7B params.',
    url: 'https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf',
    filename: 'mistral-7b-instruct-v0.2.Q4_K_M.gguf',
    sizeBytes: 4_370_000_000,
    sizeLabel: '~4.37 GB',
    quantization: 'Q4_K_M',
    parameters: '7B',
  },
  {
    id: 'synatra-7b-q4',
    name: 'Synatra V0.1 7B Instruct',
    description: 'Korean/English instruction-following. Strong QA and chat. 7B params.',
    url: 'https://huggingface.co/TheBloke/Synatra-V0.1-7B-Instruct-GGUF/resolve/main/Synatra-V0.1-7B-Instruct-Q4_K_M.gguf',
    filename: 'Synatra-V0.1-7B-Instruct-Q4_K_M.gguf',
    sizeBytes: 4_370_000_000,
    sizeLabel: '~4.37 GB',
    quantization: 'Q4_K_M',
    parameters: '7B',
  },
  {
    id: 'falcon-7b-q4',
    name: 'Falcon 7B',
    description: 'Open-domain LLM trained on RefinedWeb. General chat and reasoning. 7B params.',
    url: 'https://huggingface.co/tensorblock/falcon-7b-GGUF/resolve/main/falcon-7b-Q4_K_M.gguf',
    filename: 'falcon-7b-Q4_K_M.gguf',
    sizeBytes: 4_630_000_000,
    sizeLabel: '~4.63 GB',
    quantization: 'Q4_K_M',
    parameters: '7B',
  },
  {
    id: 'qwen2.5-7b-q4',
    name: 'Qwen 2.5 7B',
    description: 'Multilingual instruct. Excellent at math, code, logic. 7B params.',
    url: 'https://huggingface.co/kaetemi/Qwen2.5-7B-Q4_K_M-GGUF/resolve/main/qwen2.5-7b-q4_k_m.gguf',
    filename: 'qwen2.5-7b-q4_k_m.gguf',
    sizeBytes: 4_680_000_000,
    sizeLabel: '~4.68 GB',
    quantization: 'Q4_K_M',
    parameters: '7B',
  },

  // ===== HIGHEST (8B) =====
  {
    id: 'llama3-8b-q4',
    name: 'Meta Llama-3 8B',
    description: 'Advanced chat/instruction. Multilingual. ~2 tokens/sec on mobile. 8B params.',
    url: 'https://huggingface.co/psuplj/Meta-Llama-3-8B-Q4_K_M-GGUF/resolve/main/Meta-Llama-3-8B-Q4_K_M.gguf',
    filename: 'Meta-Llama-3-8B-Q4_K_M.gguf',
    sizeBytes: 4_920_000_000,
    sizeLabel: '~4.92 GB',
    quantization: 'Q4_K_M',
    parameters: '8B',
  },
  {
    id: 'qwen3-8b-q4',
    name: 'Qwen3 8B',
    description: 'Multilingual LLM. Excellent for code, math, and reasoning tasks. 8B params.',
    url: 'https://huggingface.co/Aldaris/Qwen3-8B-Q4_K_M-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf',
    filename: 'Qwen3-8B-Q4_K_M.gguf',
    sizeBytes: 5_030_000_000,
    sizeLabel: '~5.03 GB',
    quantization: 'Q4_K_M',
    parameters: '8B',
  },
];
